### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by giovannigras1993** [sy1vain/cordova-plugin-osc#1]
I'm trying to use this plugin in my project. I'm creating an instance (new OSCSender('test', 'test')) but I get the error 'OSCSender not defined'. 

Is there something I'm doing wrong or is there a problem with the plugin?

**Comment by sy1vain** [comment]
Which platform are you developing for / running / testing on?

It seems it can't find the needed js files, are you sure the plugin is added correctly to your project?

**Comment by giovannigras1993** [comment]
Hi sy1vain, I installed the plugin correctly. When I try it in the chrome console it works perfectly. But when I do it in index.js after the app initialization it gives the not defined error. 

![schermafbeelding 2015-10-23 om 15 17 07](https://cloud.githubusercontent.com/assets/8546220/10694515/e0f6a876-799e-11e5-9332-213c830f83a3.png)

Developing on android by the way

**Comment by sy1vain** [comment]
To be sure: it only works on android and iOS, not on desktop.

I used it a lot of times in external files, but haven't used it in a while to be honest.

**Comment by giovannigras1993** [comment]
So testing in Chrome wouldn't work ? 

Could you maybe send an example of how you used it before? It would really help me and I'd really appreaciate it!

**Comment by sy1vain** [comment]
No, you need to run it on an Android or iOS device. I created this plugin before the browser-support, so skipped on that.

On how I use it:

**Sender**

```
var oscSender = new OSCSender("192.168.16.255", 8383);
oscSender.send('/test', ['list', 'of', 'things']);
```

You can a success and error callback as well, full function signature: `function send(address, data, successCallback, errorCallback)`

**Listener**

```
var oscListener = new OSCListener(8383);
oscListener.startListening(
    function(){
        oscListener.on('/test', function(data){
            console.log(data);
        });
    },
    function(error){
        app.error(error);
    }
);
```

So you need to set this up a bit more.
- create listener with a port
- start listening and you pass a success and a failure function
- once the listening is successful you can add events to receive

Hope this helps
