### ISSUE TITLE
Is it possible to have the OSC server continue to listen on iOS when the device is locked?

### ISSUE THREAD

**Issue by BenBergman** [sy1vain/cordova-plugin-osc#3]

**Comment by sy1vain** [comment]
Not sure about this. I think iOS limits the use of network usage when going into locked mode. I know it is possible for small fetches, but in this case it will only receive.

**Comment by BenBergman** [comment]
All that I need my iOS app to do is receive messages and fire local notifications based on that. Did you mean that this might be possible? Or that I would have to make my app send out requests in the background?

This app isn't going on the App Store, so no need to follow Apple guidelines. Any suggestions for how I might get the OSC library to continue receiving in the background? I'm pretty new to iOS dev so I'm very appreciative of your help.

**Comment by BenBergman** [comment]
I found a Cordova plugin that enables perpetual background activity and it seems to be working fine for me with this OSC plugin (thanks for the great plugin!).

https://github.com/katzer/cordova-plugin-background-mode

**Comment by BenBergman** [comment]
I found a Cordova plugin that enables perpetual background activity and it seems to be working fine for me with this OSC plugin (thanks for the great plugin!).

https://github.com/katzer/cordova-plugin-background-mode

**Comment by sy1vain** [comment]
Cool, thanks for the tip!
