### ISSUE TITLE
The Plugin is not send from iOS

### ISSUE THREAD

**Issue by ibuioli** [sy1vain/cordova-plugin-osc#4]
Hi, I builded the example of this plugin and it works excellent on Android device. But on iPhone this usually crash and send nothing. On xCode console it give this error:

`[OSCConnection sendPacket:toHost:port] can only be called on a UDP connection that has been binded.`

I found this is related to CocoaOSC but there isn't more information. What is means with "bind UDP connection"? I used the IP of my computer with a simple OSC monitor working it, on Android the data is sended, on iPhone not.

I tested it on iPhone 6, this is the code, but is exactly the example code:

```var app = {
    initialize: function() {
        document.addEventListener('deviceready', this.onDeviceReady.bind(this), false);
    },
    onDeviceReady: function() {
        this.receivedEvent('deviceready');

        var osc = new OSC();

        osc.send({
            remoteAddress: '192.168.1.231',
            remotePort: 8000,
            address: '/test',
            arguments: ['start']
        });

        setInterval(function(){
          osc.send({
              remoteAddress: '192.168.1.231',
              remotePort: 8000,
              address: '/test',
              arguments: ['testing']
          });
        }, 1000);
    },
    receivedEvent: function(id) {
        var parentElement = document.getElementById(id);
        var listeningElement = parentElement.querySelector('.listening');
        var receivedElement = parentElement.querySelector('.received');

        listeningElement.setAttribute('style', 'display:none;');
        receivedElement.setAttribute('style', 'display:block;');

        console.log('Received Event: ' + id);
    }
};

app.initialize();
```

**Comment by sy1vain** [comment]
To send UDP packets a socket needs to be bound to a port. The Android implementation does this automatically, the iOS implementation does not. But there is a simple work around. Just add a `osc.startListening(....)` call right after you create the object. The port doesn't really matter, but if you intend to actuality receive stuff as well, that should match. Does that work for you?

**Comment by ibuioli** [comment]
Yes, that works, I didn't know that happen on iOS. Thanks for the quick solution.
