### ISSUE TITLE
ARC Semantic Issue iOS 13

### ISSUE THREAD

**Issue by josiaho** [sy1vain/cordova-plugin-osc#5]
Hello, this plugin worked great with iOS 12, but in iOS 13 I'm receiving an Xcode build fail due to an apparent conflict in the Foundation Framework:

"../OSCConnection.m:111:12: Multiple methods named 'localPort' found with mismatched result, parameter type or attributes"

Has anyone else experienced this?

Thanks!!

**Comment by sy1vain** [comment]
Yeah, I have it too. I will test and try to fix it later, but for now, try this:

Change:

https://github.com/sy1vain/cordova-plugin-osc/blob/153607cb65b86d79d43133e7f16c642f49916130/src/ios/CocoaOSC/OSCConnection.m#L111

to 

`return (tcpSocket ? [tcpSocket localPort] : [udpSocket localPort]);`

**Comment by josiaho** [comment]
Perfect - thanks so much!

**Comment by sy1vain** [comment]
Let's keep this issue open until it is actually implemented and published

**Comment by josiaho** [comment]
👍

Josiah

**Comment by sy1vain** [comment]
Closed with 462c94d666365b334806ee2ecf50e125912ee9eb
