### ISSUE TITLE
OSC is not defined

### ISSUE THREAD

**Issue by toujours** [sy1vain/cordova-plugin-osc#6]
hello good afternoon, when you add the plugin using cordova plugin add cordova-plugin-osc shows me an message  OSC is not defined

**Comment by sy1vain** [comment]
Can you give some more info? Which platform, some example code which isn't working etc.

**Comment by davidferoli** [comment]
Hi, I also see this error in cordova 9.0.0 and cordova-android 8.0.0

**Comment by sy1vain** [comment]
Do you have some non-working example code?

Are you calling the OSC code after the 'deviceready' event? Because before that no plugin is available.

**Comment by Autr** [comment]
Hello, also have this issue; is the a constructor "OSC" supposed to be present on the window object?

```

	document.addEventListener("deviceready", () => {
		ready = true;
		console.log('[Cordova]', cordova); // -> object
		console.log('[Cordova:OSC]', OSC); // -> undefined
	})


```

**Comment by sy1vain** [comment]
@autr On which platform are you experiencing this. I created a new project and copied your code to the main js file and it gives me: 

```
[Cordova] [object Object]
[Cordova:OSC] function (){
  this.instanceID = OSC_ID++;
}
```

**Comment by sy1vain** [comment]
Closing - inactive thread
